export interface SenhafferCabecera {
    idSistema: string;
    masterVuelo: string;
    masterTransportista: string;
    masterNro: string;
    masterFecha: string;
    nroManifiesto: string;
    viaTransporte: string;
    fechaArribo: string;
    pesoDeclarado: string;
    locacionEmbarque: string;
    locacionDesembarque: string;
    locacionEntrega: string;
    locacionRecepcion: string;
    hawb: string;
    fecha: string;
    ingreso: string;
    codigo: string;
    barra: string;
    destinatarioNombre: string;
    destinatarioDireccion: string;
    destinatarioCiudad: string;
    destinatarioPais: string;
    destinatarioTelefono: string;
    destinatarioEmail: string;
    destinatarioRut: string;
    contenido: string;
    valorUsd: string;
    pesoBruto: string;
    cantidad: string;
    estado: string;
    estadoCorto: string;
    ingresoFisico: string;
    nroDips: string;
    flete: string;
    fechaEntregaUm: string;
    transportistaUm: string;
    idExterno: string;
    bagId: string;
    nroBatch: string;
    taxType: string;
}

export const estructuredSenhaffer: SenhafferCabecera = {
    idSistema: '',
    masterVuelo: '',
    masterTransportista: '',
    masterNro: '',
    masterFecha: '',
    nroManifiesto: '',
    viaTransporte: '',
    fechaArribo: '',
    pesoDeclarado: '',
    locacionEmbarque: '',
    locacionDesembarque: '',
    locacionEntrega: '',
    locacionRecepcion: '',
    hawb: '',
    fecha: '',
    ingreso: '',
    codigo: '',
    barra: '',
    destinatarioNombre: '',
    destinatarioDireccion: '',
    destinatarioCiudad: '',
    destinatarioPais: '',
    destinatarioTelefono: '',
    destinatarioEmail: '',
    destinatarioRut: '',
    contenido: '',
    valorUsd: '',
    pesoBruto: '',
    cantidad: '',
    estado: '',
    estadoCorto: '',
    ingresoFisico: '',
    nroDips: '',
    flete: '',
    fechaEntregaUm: '',
    transportistaUm: '',
    idExterno: '',
    bagId: '',
    nroBatch: '',
    taxType: '',
}